In [1]:
## Data Analysis libraries
import pandas as pd
import numpy as np

## Data Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns

## Ignore warnings libraries
import warnings 
warnings.filterwarnings('ignore')

## Read Salaries.csv as a dataframe called sal

In [59]:
sal = pd.read_csv(r'C:\Users\admin\Desktop\edyoda\files\Data wrangling\Salaries.csv')

## Check the head of the DataFrame

In [60]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   
2  212739.13   106088.18    16452.6      NaN  335279.91         335279.91   
3    77916.0    56120.71   198306.9      NaN  332343.61         332343.61   
4   134401.6      9737.0  182234.59      NaN  326373.19         326373.19   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN  
2  2011    NaN  San Francisco    NaN  
3  2011    NaN  San Francisco    NaN  
4  2011    NaN  San Francisco    NaN

## Use the .info() method to find out how many entries there are.

In [61]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148049 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB


## What is the average BasePay ?

In [62]:
sal['BasePay'].unique()

array([167411.18, 155966.02, 212739.13, ..., '6.04', '15.50',
       'Not Provided'], dtype=object)

In [63]:
dic1={'Not Provided': np.nan}
dic1

{'Not Provided': nan}

In [64]:
sal['BasePay']=sal['BasePay'].replace(dic1)
sal['BasePay'].unique()

array([167411.18, 155966.02, 212739.13, ..., '17.26', '6.04', '15.50'],
      dtype=object)

In [65]:
sal['BasePay']=sal['BasePay'].astype('float')
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(4), int64(2), object(7)
memory usage: 14.7+ MB


In [66]:
sal['BasePay'].mean()

66325.4488404877

## What is the highest amount of OvertimePay in the dataset ?

In [67]:
sal['OvertimePay']=sal['OvertimePay'].replace(dic1)
sal['OvertimePay'].unique()

array([0.0, 245131.88, 106088.18, ..., '102.70', '56.77', nan],
      dtype=object)

In [68]:
sal['OvertimePay']=sal['OvertimePay'].astype('float')
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(5), int64(2), object(6)
memory usage: 14.7+ MB


In [69]:
sal['OvertimePay'].max()

245131.88

## What is the job title of JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll).

In [70]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

## How much does JOSEPH DRISCOLL make (including benefits)?

In [71]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

## What is the name of highest paid person (including benefits)?

In [72]:
sal[['TotalPayBenefits','EmployeeName']].max()

TotalPayBenefits     567595.43
EmployeeName        Zuri Jones
dtype: object

## What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?

In [73]:
sal[['TotalPayBenefits','EmployeeName']].min()

TotalPayBenefits             -618.13
EmployeeName        A BERNARD FATOOH
dtype: object

## What was the average (mean) BasePay of all employees per year? (2011-2014) ?

In [76]:
sal.groupby('Year')['BasePay'].agg('mean')

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

## How many unique job titles are there?

In [77]:
sal['JobTitle'].nunique()

2159

 ## What are the top 5 most common jobs?

In [79]:
sal['JobTitle'].value_counts().head()

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

## How many Job Titles were represented by only one person in 2013?

In [80]:
(sal[sal['Year']==2013]['JobTitle'].value_counts()==1).sum()

202

## How many people have the word Chief in their job title? (This is pretty tricky)

In [82]:
sal['JobTitle'].apply(lambda str:('chief' in str.lower())).sum()

627